[package]
name = "naths_fat_fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

publish = false

[dependencies]
fuser = {version = "0.12.0", features = ["abi-7-31"]}
libc = "0.2.139"